services:
  nginx:
    image: bitnami/nginx:latest
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - "80:80"
    volumes:
      - ./server_block.conf:/opt/bitnami/nginx/conf/server_blocks/php-test.conf

  phpfpm:
    image: bitnami/php-fpm:latest
    networks:
      - app-tier
    volumes:
      - ./src:/app
    depends_on:
      - mysql
    environment:
      - PHP_ENABLE_OPCACHE=no
      - DB_HOST=mysql
      - DB_NAME=orders_db
      - DB_USER=root
      - DB_PASS=root
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-tier

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8001:80"
    depends_on:
      - mysql
    networks:
      - app-tier


volumes:
  mysql_data:

networks:
  app-tier:
    driver: bridge