services:
  nginx:
    image: bitnami/nginx:latest
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server_block.conf:/opt/bitnami/nginx/conf/server_blocks/php-test.conf

  phpfpm:
    image: bitnami/php-fpm:latest
    networks:
      - app-tier
    volumes:
      - ./src:/app

networks:
  app-tier:
    driver: bridge